apiVersion: apps/v1
kind: Deployment
metadata:
  name: svc1-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8-svc1
  template:
    metadata:
      labels:
        app: k8-svc1
    spec:
      containers:
        - name: k8-svc1
          image: tanvirriyad/k8-svc1:latest
          ports:
            - containerPort: 5000
